name: Test

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - 'exp_*'
  pull_request:
    branches-ignore:
      - 'exp_*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: justinisrael/openimageigo:latest-oiio_3.1

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Try to pull image
        id: pull_image
        continue-on-error: true
        run: |
          docker pull "$DOCKER_IMAGE"

      - name: Set up Docker Buildx
        if: steps.pull_image.outcome != 'success'
        uses: docker/setup-buildx-action@v2

      - name: Build Image (only if pull failed)
        if: steps.pull_image.outcome != 'success'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_IMAGE }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          docker run --rm \
            -v $PWD:/workdir \
            -v $PWD/.cache/go-build:/root/.cache/go-build \
            -v $PWD/.cache/go/pkg:/go/pkg \
            "$DOCKER_IMAGE"
